---
- hosts: 127.0.0.1
  connection: local
  gather_facts: false
  vars:
    k3s_version: v1.18.6+k3s1

  tasks:

  - name: copy gen-hostname script
    copy:
      content: |
        #!/bin/bash
        ip_cidr=$(ip addr show $1 | grep global | awk '{print $2}' )

        regex_mgmt="^10\.40\.1\.[0-9]{1}/.*$"
        regex_worker="^10\.40\.0\.[0-9]{2}/.*$"
        regex_ctrl="^10\.40\.0\.1[0-9]{2}/.*$"

        if [[ "${ip_cidr}" =~ $regex_mgmt ]]; then
          echo "mgmt$(echo $ip_cidr | sed 's/\/.*//' | cut -f4 -d\. | awk {'print $1-1'})"
        elif [[ "${ip_cidr}" =~ $regex_worker ]]; then
          echo "worker$(echo $ip_cidr | sed 's/\/.*//' | cut -f4 -d\. | awk {'print $1-10'})"
        elif [[ "${ip_cidr}" =~ $regex_ctrl ]]; then
          echo "ctrl$(echo $ip_cidr | sed 's/\/.*//' | cut -f4 -d\. | awk {'print $1-100'})"
        else
          echo "unknown-node"
        fi
      dest: /usr/local/bin/gen-hostname
      mode: '0755'
      owner: root
      group: root

  - name: copy cloud-init metadata file into place for NoCloud
    copy:
      content: |
        #cloud-config

        package_update: True

        package_reboot_if_required: True

        # packages:
        # - ca-certificates

        ssh_pwauth: True

        locale: en_GB.UTF-8
        locale_configfile: /etc/default/locale

        timezone: Europe/London

        # we will handle these separately via script later
        preserve_hostname: True
        manage_etc_hosts: False

        resolv_conf:
          nameservers: ['10.0.1.254', '8.8.4.4', '8.8.8.8']
          searchdomains:
          - b5y.gs
          domain: b5y.gs
          options:
            rotate: True
            timeout: 1

        # generate hostname based off IP
        runcmd:
        - [ sh, -c, 'hostnamectl set-hostname $(/usr/local/bin/gen-hostname eth0)' ]
        - [ sh, -c, 'echo 127.0.0.1 localhost > /etc/hosts' ]
        - [ sh, -c, 'HOST=$(/usr/local/bin/gen-hostname eth0) echo 127.0.1.1 ${HOST}.b5y.gs ${HOST} >> /etc/hosts' ]
        - [ sh, -c, 'passwd -l ubuntu' ]

        power_state:
          delay: "now"
          mode: reboot
          message: Rebooting to enable cgroups
          timeout: 30

        final_message: "The BEAST has arisen!"

        # end of user-data

      dest: /etc/cloud/cloud.cfg.d/999-beast.cfg

  - name: Enable IPv4 forwarding (as k3s needs it)
    sysctl:
      name: net.ipv4.ip_forward
      value: "1"
      state: present
      reload: false

  - name: Enable cgroup via boot commandline if not already enabled
    lineinfile:
      path: /boot/firmware/cmdline.txt
      backrefs: true
      regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
      line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'

  - name: Download k3s binary arm64
    get_url:
      url: https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/k3s-arm64
      dest: /usr/local/bin/k3s
      owner: root
      group: root
      mode: 0755

  - name: Update apt repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Upgrade all packages
    apt: upgrade=dist force_apt_get=yes

  - name: Create bqw user
    user:
      name: bqw
      password: $6$TMclPsR3VoTXL5$ZoUUM8QKDGb5D5fEnNzPR8i4LbMPxjN2aoAdRilkSQy9eRfRJ.17LmeTIadLywesePc0NDfeRJlyFJhv/MGMQ1
      password_lock: false
      comment: Bradley Wood
      shell: /bin/bash
      groups: users,admin

  - name: Create bqw's .ssh directory
    file:
      path: /home/bqw/.ssh
      owner: bqw
      group: bqw
      state: directory
      mode: '0700'

  - name: copy bqw's public key into place
    copy:
      content: |
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDGs8F0zbHCStQQrVP106igaD6kZl7aoBRUSkPx6TGb4/fcRBctBzy/W3iJis5cFrCO2lxRf4gJjdfUuexNpcLsVGJEcW2GNA0HWSv5GC3wQRn+RxspxKIC9Los7M0z/35yYzAqaPfrthOMYqrjA6dXlQ1geLyteKI6Q5v+cyNLGnQMG9PvBEYK4zerL/fd5fCdY3TDUDy7pMpBuODdZBNtwrYVABh69I/CqW7FwALyjOtmfsNSTULoCyA6t7UyRbknKVzDU3nDFJtp2pxTvQ/fnAEP2r8vwPPSiWqke6AkO0zKSfPnosOB3gJd8W2/OAAEvy++XIutYmNwP3LjHkwwV0/Nh9fkp28HtcgTvDUp+Sdc3MQH2OqMZsJkHlHmA0FYHU6ZhjOtXexSjBw8AmwwMeRlC3ZHLKSiLpmye9OSMXBevNJvlz8TrL2DOfupEjRWfqOLTIfXz/4n0178vH546R6mAAnS9zP9pUr5UXFjLkMD7TlNGRf1ngOzlLugV8E= beast
      dest: /home/bqw/.ssh/authorized_keys
      owner: bqw
      group: bqw
      mode: '0600'

  - name: copy bqw's sudoer's into place
    copy:
      content: |
        bqw ALL=(ALL) NOPASSWD:ALL
      dest: /etc/sudoers.d/95-bqw
      owner: root
      group: root
      mode: '0440'

  - name: Remove useless packages from the cache
    apt:
      autoclean: true

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: true
